### PR TITLE
Improved /cash precision to 4 decimal and added Connection.py feature

### PR DESCRIPTION
**Pull request by anandpskerala**

### CODE REVIEW

**Comment by anandpskerala** [comment]
#4 updated

**Comment by TsunayoshiSawada** [comment]
The connection py requires that other functions be updated to support the chat id based connection too. 

Your commit is missing vital updates. 
Simply copy-pasting a py just might not work.
The sql file for connection is missing entirely 

The edit to cash converter can be approved but the connection.py will end up in disaster due to missing commits.

**Comment by anandpskerala** [comment]
It's not completed I had no time to finish it.soon it will be completed.

**Comment by TsunayoshiSawada** [comment]
Avoid partial commits 
And sort commits based on type. this particular pull request has two diff things. 

Im closing this pull - make one for converter and one for connection ( it should include all changes )

**Pull request closed without merging**
