### PR TITLE
config.py

### PR DESCRIPTION
**Pull request by ghost**
from sample_config import Config

class Development(Config):
  APP_ID = 
  API_HASH = ""
  TG_BOT_TOKEN_BF_HER = ""
  TG_BOT_USER_NAME_BF_HER = "@"
  UB_BLACK_LIST_CHAT = [
    -1001220993104,
    -1001365798550,
    -1001158304289,
    -1001212593743,
    -1001195845680,
    -1001330468518,
    -1001221185967,
    -1001340243678,
    -1001311056733,
    -1001135438308,
    -1001038774929,
    -1001070622614,
    -1001119331451,
    -1001095401841
  ]
  # specify LOAD and NO_LOAD
  LOAD = []
  NO_LOAD = []

### CODE REVIEW

**Comment by DragSama** [comment]
you just leaked your config

**Comment by DragSama** [comment]
Nice.

**Comment by CustomIcon** [comment]
@nawazish095 thanks

**Comment by CustomIcon** [comment]
@nawazish095 .neko

**Comment by TsunayoshiSawada** [comment]
Go change your bot token and go push this on your own branch.
Hope that your fork/clone/kang whatever is open repo though.

**Comment by CustomIcon** [comment]
@TsunayoshiSawada man im stealing his session if yall are okay

**Comment by Netkas** [comment]
@pokurt Oh no.

**Comment by Dank-del** [comment]
@nawazish095 Sunnimasen.....wtf?

**Comment by Netkas** [comment]
I love the label.

**Comment by CustomIcon** [comment]
@Netkas based king

**Comment by Dank-del** [comment]
@Netkas Yeeet

**Comment by Dank-del** [comment]
@pokurt No u

**Comment by DragSama** [comment]
How did he even manage to push his uniborg repo config to saitama

**Comment by architdate** [comment]
poop

**Comment by CustomIcon** [comment]
@architdate peepeepooopoo stinky

**Comment by shinigamiKira** [comment]
tehc

**Comment by anshuman852** [comment]
@nawazish095 What in the actual fuck man

**Pull request closed without merging**
