### PR TITLE
Add a workflow to Autoformat code

### PR DESCRIPTION
**Pull request by Accipiter7**

### CODE REVIEW

**Comment by Dank-del** [comment]
@Accipiter7 Wow

**Comment by Accipiter7** [comment]
@Accipiter7 style option are google pep8 yapf facebook or any other custom

**Comment by starry69** [comment]
@Accipiter7

**Comment by CustomIcon** [comment]
@Accipiter7

**Comment by TsunayoshiSawada** [comment]
@Accipiter7 test

**Comment by TsunayoshiSawada** [comment]
@Accipiter7 test2

**Comment by TsunayoshiSawada** [comment]
one more test.

**Comment by CustomIcon** [comment]
@TsunayoshiSawada bruh

**Comment by CustomIcon** [comment]
wait .. did you pulled it 3 times..

**Pull request merged**
