### PR TITLE
[Admin.py] Get chatusername with proper link when using invite command

### PR DESCRIPTION
**Pull request by davinash97**

### CODE REVIEW

**Review by Accipiter7 — COMMENTED** [review]
use f-string instead of format and use https protocol
like this :

f"https://t.me/{chat.username}"

**Comment by davinash97** [comment]
Ok

**Comment by TsunayoshiSawada** [comment]
@davinash97 Nice work btw.

**Comment by davinash97** [comment]
> @davinash97 Nice work btw.

Thanks for the appreciation mate, i am new to python so feel free to correct me too.

**Comment by TsunayoshiSawada** [comment]
@davinash97 We are not mates, no mating.

**Comment by Accipiter7** [comment]
@TsunayoshiSawada good work bruh

**Comment by TsunayoshiSawada** [comment]
@Accipiter7 Stalker detected!

**Comment by Accipiter7** [comment]
> @Accipiter7 Stalker detected!

Am i a Stalker?

**Comment by TsunayoshiSawada** [comment]
@Accipiter7 si

**Comment by Accipiter7** [comment]
@TsunayoshiSawada ???

**Pull request merged**
