### PR TITLE
abuse vibe check

### PR DESCRIPTION
**Pull request by CustomIcon**
abuse vibe check

### CODE REVIEW

**Comment by TsunayoshiSawada** [comment]
@AmaanAhmed Done

**Comment by CustomIcon** [comment]
@TsunayoshiSawada .

**Comment by Dank-del** [comment]
@TsunayoshiSawada Yeet

**Comment by ajhalili2006** [comment]
Why abusing vibe checks? And WTF @Dank-del and @AmaanAhmed yeeting around?

**Comment by Dank-del** [comment]
@AndreiJirohHaliliDev2006 :c

**Comment by CustomIcon** [comment]
@Dank-del its okay you wont go to jail

**Pull request merged**
