### PR TITLE
Shiken

### PR DESCRIPTION
**Pull request by DragSama**

### CODE REVIEW

**Comment by CustomIcon** [comment]
@DragSama he really did it

**Comment by Dank-del** [comment]
@ArazoraTaro Lmao

**Comment by TsunayoshiSawada** [comment]
@DragSama Oof size 100

**Comment by Dank-del** [comment]
@TsunayoshiSawada Kekku

**Comment by anshuman852** [comment]
@TsunayoshiSawada Wau

**Pull request merged**
