### PR TITLE
pulling all changes from saitama to tauka-sama

### PR DESCRIPTION
**Pull request by asifuvvu**

### CODE REVIEW

**Comment by TsunayoshiSawada** [comment]
Pulling changes gone wrong and you pushed instead.

**Comment by asifuvvu** [comment]
this is a test PR just to show how its done

**Comment by TsunayoshiSawada** [comment]
Well its done wrong as it says pulling changes "from" and you are actually pushing "to" Saitama.

**Comment by asifuvvu** [comment]
> Well its done wrong as it says pulling changes "from" and you are actually pushing "to" Saitama.

tbh i dont even know what i am doing rn . sorry if i am bothering you . as of now you don't support fork i have to go through all past messages of how you have helped others . kek i am bad at this . and i'll never again do something blunter like this *at least i'll try

**Comment by TsunayoshiSawada** [comment]
You are bothering our repo with unnecessarty alerts.
Make a test repo > fork it > play around there until you learn it. 

DO NOT TEST ON OTHERS REPO

**Pull request closed without merging**
