### PR TITLE
Send eval output as a file.

### PR DESCRIPTION
**Pull request by SHRE-YANSH**
When the evaluation's output exceeds the Telegram API limit, bot will send the output as a text file.

### CODE REVIEW

**Comment by starry-shivam** [comment]
Tg max text length its 4096 not 2000 btw

**Comment by SHRE-YANSH** [comment]
@starry69 I know about the limit but the default value in Saitama was 2000 so thought to remain with that.

**Comment by starry-shivam** [comment]
Hmm fair enough...

**Comment by TsunayoshiSawada** [comment]
This is being pushed to master branch, please push this to "[Shiken](https://github.com/AnimeKaizoku/SaitamaRobot/tree/shiken)" branch.

**Pull request closed without merging**
