### PR TITLE
May solve ValueError

### PR DESCRIPTION
**Pull request by Meow80132654**
Adding those 5 individual emojis into the list may solve the value error IDK change at your own risk

### CODE REVIEW

**Comment by CustomIcon** [comment]
@Meow80132654 lets see

**Comment by Meow80132654** [comment]
@AmaanAhmed okie

**Comment by TsunayoshiSawada** [comment]
pls add changes to shiken branch and not master. 
I need to see how to block anyone from opening Pr's on master.

**Comment by DragSama** [comment]
Delete master

**Pull request closed without merging**
