### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by ranmiella**

### CODE REVIEW

**Comment by TsunayoshiSawada** [comment]
What are you trying to do here?

**Comment by CustomIcon** [comment]
damn... this is like my only will to live rn xD

**Comment by ranmiella** [comment]
how to change text at /start command


Pada tanggal Min, 19 Jul 2020 pukul 13.04 Sawada Tsunayoshi <
notifications@github.com> menulis:

**Comment by TsunayoshiSawada** [comment]
Step1: Fork the bot. 
Step2: Push your stuff on your own fork and not our repo.
Step3: Stop asking help on a closed pull request.

You need to "fork" the repo if you want to edit stuff and then deploy that forked repo. 
Please do not debate the topic here further, if you are confused either visit the support chat or open an issue.

**Pull request closed without merging**
