### PR TITLE
[pro devs] Example of what not to do.

### PR DESCRIPTION
**Pull request by ogsamrat**

### CODE REVIEW

**Comment by TsunayoshiSawada** [comment]
Don't do Drugs. 
Or this happens.

**Comment by Dank-del** [comment]
Wow

**Comment by ogsamrat** [comment]
Ehh

**Comment by SeedhaMaut** [comment]
Mai ghus ke fatu jaise TTP

**Comment by EmiliaDevs** [comment]
Sawada humara neta hai Sabka mu me leta hai

**Comment by TsunayoshiSawada** [comment]
^ When you already are a proven noob but want to try salvage your nonexisttent rep.

**Comment by SeedhaMaut** [comment]
Hath chorunga ye nahi internet ka beef bhai

**Comment by TsunayoshiSawada** [comment]
Come back when you can type a sentence.

**Comment by SeedhaMaut** [comment]
Kya fayada kar payega nai tu
Haar jayega marwayega bhi tu
Maar khayega lad payega nai tu

**Comment by SeedhaMaut** [comment]
KR Doller Sign (Maloom Hai Na) ?

**Comment by TsunayoshiSawada** [comment]
> KR Doller Sign (Maloom Hai Na) ?

Noone knows shitty stuff. 
Also, great english "doller"

**Pull request closed without merging**
