### PR TITLE
[core] Google Translator from Mia

### PR DESCRIPTION
**Pull request by anandvfcvijay**

### CODE REVIEW

**Comment by architdate** [comment]
why create #1 and #2 both? don't they serve the same purpose?

**Comment by anandvfcvijay** [comment]
Sorry it was an accidental mistake due to network error

**Comment by anandvfcvijay** [comment]
One is the requirement  [googletrans]

**Comment by architdate** [comment]
Yeah that can be pip installed, so not an issue there. If possible can you remove the commented out code. Apart from that it looks fine and ready to merge for me

**Comment by anandvfcvijay** [comment]
Ok

**Comment by TsunayoshiSawada** [comment]
Anand - Also include an edit to requirements.txt and we will collectively merge all of this.

**Comment by anandvfcvijay** [comment]
Just add googletrans as requirement for the Translator

**Comment by architdate** [comment]
When you are deleting the comments in the above file, just also add googletrans to requirements.txt like you did in #1 once that's done, i'll squash and merge. Thanks for ur contribution

**Pull request closed without merging**
